const DATA = {
  ...DATA_DASHBOARD,
  ...DATA_CONTAINERS,
  ...DATA_RESOURCES,
  ...DATA_ROUTES,
  ...DATA_DRIVERS,
  ...DATA_HUBS_OPS,
  ...DATA_CUSTOMERS,
  ...DATA_REPORTS,
  templates: DATA_TEMPLATES,
};
